import express from "express";
import "dotenv/config";
import cors from "cors";

const movie = [
  {
    id: 1,
    title: "Business Proposal",
    year: 2022,
    genre: ["Romance", "Comedy"],
    rating: 9.7,
    director: "Park Seon-ho",
    actors: ["Kim Se-jeong", "Ahn Hyo-seop", "Seol In-ah", "Kim Min-kyu"],
    plot: "Shin Ha-ri (Kim Se-jeong) melakukan kencan buta dengan menyamar sebagai temannya dengan tujuan 'ditolak' oleh calon pasangan temannya. Tapi rencana menjadi kacau ketika orang yang dia temui ternyata adalah Kang Tae-mu (Ahn Hyo-seop) –CEO perusahaan tempat Ha-ri bekerja.",
    poster:
      "https://i.pinimg.com/564x/0f/52/ab/0f52ab7afa119ac22a103244208e42d4.jpg",
    trailer: "https://youtu.be/XRU1BtiulXw?si=wz6EdX6rxqNBHwtW",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Kross Pictures and Kakao Entertainment",
  },
  {
    id: 2,
    title: "Queen Of Tears",
    year: 2022,
    genre: ["Romance", "Comedy Romance"],
    rating: 9.8,
    director: "Jang Young-woo",
    actors: ["Kim Ji-won", "Kim Soo-hyun"],
    plot: "Queen of Tears mengisahkan Baek Hyun-woo, seorang pengacara sukses, dan pernikahannya dengan Hong Hae-in. Meski awalnya tampak sempurna, dalam tiga tahun pernikahan, Hyun-woo mengalami tekanan dari keluarga Hae-in dan merasa tidak mendapat dukungan dari istrinya.",
    poster:
      "https://i.pinimg.com/736x/cb/61/03/cb610365ad8830243ce88b1f98b63d20.jpg",
    trailer: "https://youtu.be/tNhIiisjjJg?si=UpEyYHcctOW9Of-2",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Studio Dragon",
  },
  {
    id: 3,
    title: "Revenge Of Others",
    year: 2022,
    genre: ["Action", "Romance"],
    rating: 8.4,
    director: "Kim Yoo-jin",
    actors: ["Park Solomon", "Shin Ye-eun"],
    plot: "Revenge of Others atau Third Person Revenge mengusung genre thriller tentang balas dendam anak remaja. Berkisah tentang Ok Chan Mi (Shin Ye Eun), yang berusaha untuk mengungkapkan kebenaran di balik kematian saudara kembarnnya.",
    poster:
      "https://i.pinimg.com/564x/53/f0/31/53f03141f194e5b9f4e4b46d78a05b43.jpg",
    trailer: "https://youtu.be/9gjMIeMksnQ?si=KsGrvkPUhHAQbt4m",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Seoul Broadcasting System",
  },
  {
    id: 4,
    title: "Night Has Come",
    year: 2023,
    genre: ["Thriller", "Mystery", "Revenge"],
    rating: 9.6,
    director: "Lim Dae-Woong",
    actors: ["Cha Woo-min", "Lee Jae-in"],
    plot: "pembunuhan mafia dalam dunia permainan tiba-tiba terjadi secara riil di kehidupan nyata dan begitu mematikan.",
    poster:
      "https://i.pinimg.com/736x/1c/24/7a/1c247a41481d17e5e3917fdd0fbce132.jpg",
    trailer: "https://youtu.be/yNkfTd8R7x0?si=-L-KgN_uA9JXirW3",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Viu",
  },
  {
    id: 5,
    title: "Guardian: The Lonely and Great God",
    year: 2016,
    genre: ["Drama", "Romance", "Fiksi ilmia", "Melodrama", "Fantasi"],
    rating: 9.5,
    director: "Lee Eung-bok",
    actors: ["Gong Yoo", "Kim Go-eun", "Lee Dong-wook", "Yoo In-na"],
    plot: "menceritakan tentang Kim Shin, seorang jenderal perang yang hebat di zaman kuno. Ia dibunuh oleh raja muda yang cemburu pada kehebatannya. Kim Shin akhirnya menjadi Dokkaebi (Goblin), yang memiliki kehidupan abadi.",
    poster:
      "https://i.pinimg.com/564x/cc/2f/80/cc2f8002ca1ca32af8f0bebdb986d831.jpg",
    trailer: "https://youtu.be/6tOxnroOTWU?si=4sWw3f2S4gkq6QVa",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 6,
    title: "See You in My 19th Life",
    year: 2023,
    genre: ["Drama", "Romance", "Fantasi"],
    rating: 8.8,
    director: " Lee Na-Jeong",
    actors: ["Ahn Bo-hyun", "Shin Hye-sun"],
    plot: "seorang wanita yang ingat dengan semua kehidupannya. Dia sudah menjalankan kehidupannya selama 19 kali. Setiap dia dilahirkan kembali, dari usia 8 hingga 12 tahun, dia akan mengingat kehidupan-kehidupan sebelumnya.",
    poster:
      "https://i.pinimg.com/564x/1a/e2/97/1ae297ec621bf9646f0bfd9f4766d7ad.jpg",
    trailer: "https://youtu.be/kFXuGIcSZtA?si=yaQcoSZ77odPgGYy",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 7,
    title: "Descendants Of The Sun",
    year: 2016,
    genre: ["Action", "Drama", "Romance", "Melodrama"],
    rating: 9.6,
    director: "	Ham Young-hoon",
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    plot: "bercerita tentang kisah cinta antara kapten pasukan khusus, Yoo Shi Jin (Song Joong Ki) dan dokter bedah Kang Mo Yeon (Song Hye Kyo).",
    poster:
      "https://i.pinimg.com/564x/b8/c2/33/b8c233c1ea3c07b24c6dcd9b711bd627.jpg",
    trailer: "https://youtu.be/wTGwjDqtfzQ?si=MxOjkwBpnIA2ZDgK",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "KBS2",
  },
  {
    id: 8,
    title: "School 2021",
    year: 2021,
    genre: ["Comedy", "Drama", "Melodrama"],
    rating: 8.9,
    director: "Jung Seung-woo",
    actors: ["Cho Yi-hyun", "Kim Yo-han", "Choo Young Woo"],
    plot: "Berkisah tentang kehidupan remaja SMA di Korea. Drama ini dibintangi Kim Yo Han, Choo Young Woo, Jo Yi Hyun, dan Hwang Bo Reum. Lengkap pula dengan jadwal tayang dan link nonton. Sinopsis drakor School 2021 berfokus pada kehidupan anak Sekolah Menengah Atas (SMA) dan segala pelik keseharian anak remaja..",
    poster:
      "https://i.pinimg.com/564x/50/23/4b/50234b54faf8b43756c9379a06b43e64.jpg",
    trailer: "https://youtu.be/SUZlRN1lQdg?si=aauCyjg9-H82XzY9",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "KBS2",
  },
  {
    id: 9,
    title: "My Roommate is A Gumiho",
    year: 2021,
    genre: ["Romace", "Comedy Romance", "Fantasi"],
    rating: 9.8,
    director: "Nam Sung Woo",
    actors: ["Lee Hyeri", "Jang Ki-yong"],
    plot: "Bercerita tentang Gumiho laki-laki yang telah hidup ratusan tahun untuk menjadi manusia, manik-manik rubahnya diambil oleh seorang mahasiswi dalam suatu kecelakaan dan memutuskan untuk tinggal bersama di sebuah rumah demi memecahkan masalah ini.",
    poster:
      "https://i.pinimg.com/564x/f3/3e/71/f33e710957c7bc260e80bad1a42b3e10.jpg",
    trailer: "https://youtu.be/Ut-TOjSgJHY?si=QjlfB9ED0xBKHxQK",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 10,
    title: "All of Us Are Dead",
    year: 2022,
    genre: ["Horor", "Drama", "Zombie apocalypse"],
    rating: 8.6,
    director: "Lee Jae-Gyu",
    actors: ["Park Solomon", "Cho Yi-hyun"],
    plot: "Sebuah SMA menjadi titik nol merebaknya wabah virus zombi. Para murid yang terperangkap pun harus berjuang untuk kabur jika tak mau terinfeksi dan berubah menjadi buas.",
    poster:
      "https://i.pinimg.com/564x/dd/97/c9/dd97c98dbce7f03a2049d6de08ac076f.jpg",
    trailer: "https://youtu.be/MwPgGgXN_jw?si=055wq_jlpKaO_G8D",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 11,
    title: "Love Alarm",
    year: 2019,
    genre: ["Drama", "Romance"],
    rating: 8.8,
    director: "Jinyee Kim ",
    actors: ["Kim So-hyun", "Song Kang", "Jung Ga-ram"],
    plot: "Di dunia saat sebuah aplikasi bisa mengingatkan orang jika ada orang sekitar yang menyukainya, Kim Jojo mengalami cinta masa remaja seraya mengatasi masalah pribadinya. ",
    poster:
      "https://i.pinimg.com/564x/de/96/ec/de96ec62e961faa596417f31181c21eb.jpg",
    trailer: "https://youtu.be/8sXTfzaLmiQ?si=Ww5byvNl02hBJjMU",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 12,
    title: "18 Again",
    year: 2020,
    genre: ["Romance", "Comedy Romance", "Drama"],
    rating: 8.5,
    director: "Jason Filardi",
    actors: ["Roh Jeong-eui", "Lee Dohyun", "Kim Ha-neul", "Ryeoun"],
    plot: "Drama Korea ini menceritakan tentang pasangan suami istri yakni Hong Dae-young dan Jung Da-jung yang telah lama menikah. Mereka dikaruniai anak kembar yang telah berusia 18 tahun. Namun pernikahan mereka diambang perceraian.",
    poster:
      "https://i.pinimg.com/564x/e8/46/bb/e846bb62b2e5d9fb313c1734166aaa81.jpg",
    trailer: "https://youtu.be/neLAy_Gpc-Y?si=mEyyshUntCWeJRWL",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "JTBC",
  },
  {
    id: 13,
    title: "Sweet Home",
    year: 2020,
    genre: ["Action", "Horor", "Fantasi"],
    rating: 8.7,
    director: "Lee Eung-Bok ",
    actors: ["Song Kang", "Go Min-si", "Go Yoon Jung"],
    plot: "Saat banyak manusia berubah menjadi monster dan menebar teror, seorang remaja bermasalah dan para tetangganya berjuang untuk hidup—dan mempertahankan kemanusiaan mereka.",
    poster:
      "https://i.pinimg.com/736x/72/ce/5a/72ce5a0bc47d4bbdf9fb77f1c391af44.jpg",
    trailer: "https://youtu.be/7rI56NmD33Y?si=Q0G_ogUXnUyDyxoj",
    runtime: "60 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 14,
    title: "Mouse",
    year: 1991,
    genre: ["Misteri", "Action", "Drama"],
    rating: 8.6,
    director: "Ahn Jae-wook",
    actors: ["Lee Seung-gi", "Park Ju-hyun", "Kyung Soo-jin"],
    plot: "ung Ba-Reum adalah seorang perwira polisi pemula, bekerja di sebuah pos polisi. Dia adalah orang yang jujur ​​dan berusaha untuk mencapai keadilan. Dia menghadapi seorang pembunuh psikopat, yang membuat seluruh bangsa ketakutan.",
    poster:
      "https://i.pinimg.com/564x/41/a2/c0/41a2c05cea28377717bd36cfd1013dae.jpg",
    trailer: "https://youtu.be/iuFYtb9J2AY?si=SkVWU9KH3h0yaZFr",
    runtime: "70 minutes",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 15,
    title: "Alchemy of Souls",
    year: 2022,
    genre: ["Action", "Drama", "Fantasi"],
    rating: 8.5,
    director: "Jeong-eun Hong",
    actors: ["Lee Jae-wook", "Go Yoon Jung", "Jung So-min"],
    plot: "Seorang penyihir wanita sakti dalam tubuh wanita buta bertemu seorang pria dari keluarga kelas atas, yang menginginkan bantuan si penyihir untuk mengubah nasibnya.",
    poster:
      "https://i.pinimg.com/564x/5e/41/23/5e41231c5ab3b9f7eb0758905fb97993.jpg",
    trailer: "https://youtu.be/nTWLBM1vrZY?si=gp8jFyW73aogGJ3-",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 16,
    title: "Hotel del Luna",
    year: 2019,
    genre: ["Drama", "War"],
    rating: 8.6,
    director: " Jeong-eun Hong",
    actors: ["Romance", "Fantasi", "Misteri"],
    plot: "Singkatnya, hotel ini sebagai tempat untuk para hantu pergi menuju alam baka dan mengalami siklus reinkarnasi. Pemilik dari hotel ajaib ini adalah Jang Man Wol yang telah hidup sejak era kerajaan alias sekitar 1000 tahun lamanya.",
    poster: "https://fakeimg.pl/220x310/ff0000",
    trailer: "https://youtu.be/zMWpcJ_n3_o?si=8GpXlXmwDJSMprGH",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 17,
    title: "Happiness",
    year: 2021,
    genre: ["Drama", "Mystery", "Action"],
    rating: 8.9,
    director: "Jo Woo-jin",
    actors: ["Park Hyung-sik", "Han Hyo-joo", "Park Joo-hee"],
    plot: "Dikisahkan, wabah zombie menyebar secara misterius di daratan Korea. Banyak orang yang terjangkit karena gigitan zombie.",
    poster:
      "https://i.pinimg.com/564x/2f/0e/83/2f0e8374e3a310e045c51ced9f7a05aa.jpg",
    trailer: "https://youtu.be/gqhUlldiLEo?si=7VlbO-DFyoHyqhmy",
    runtime: "70 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 18,
    title: "Weak Hero Class 1",
    year: 2022,
    genre: ["Drama", "Action", "Fiksi"],
    rating: 8.6,
    director: "Yoo Soo-min",
    actors: ["Park Ji-hoon", "Choi Hyun Wook", "Ryeoun"],
    plot: "Mengisahkan tentang perundungan dan korbannya yang cenderung diam, tetapi di drama satu ini mengangkat tentang perlawanan akan perundungan di sekolah. Meski Yeon Shie Eun (Park Ji Hoon) sering menjadi sasaran perundungan oleh teman-temannya, dia tak hanya diam.",
    poster:
      "https://i.pinimg.com/564x/0d/50/25/0d5025556c8258e04d158c03b63e4dbe.jpg",
    trailer: "https://youtu.be/RRDByzGXhSA?si=H7Lei-9-vc79srfc",
    runtime: "47 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Kocowa",
  },
  {
    id: 19,
    title: "Because This Is My First Life",
    year: 2017,
    genre: ["Drama", "Romance", "Comedy"],
    rating: 8.5,
    director: " Park Joon-hwa",
    actors: ["Jung So-min", "Lee Min-ki", "Park Byung-eun"],
    plot: "Alur cerita series ini tentang dua orang yang sudah menginjak usia kepala tiga yang dilema akan finansial dan memilih untuk menikah kontrak.",
    poster:
      "https://i.pinimg.com/564x/80/32/5b/80325bb71dce46b291355211b6174a05.jpg",
    trailer: "https://youtu.be/agYjoFB909A?si=Ovk7pArtcOj7o_yC",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "CJ ENM Global",
  },
  {
    id: 20,
    title: "Moving",
    year: 2023,
    genre: ["Action", "Romance", "Drama", "Fiksi"],
    rating: 9.5,
    director: "Kang Full",
    actors: ["Go Yoon Jung", "Lee Jung-ha", "Jo In-sung"],
    plot: "Moving adalah drama aksi superhero yang diadaptasi dari webtoon populer dengan judul yang sama karya Kang Full. Berkisah tentang Kim Doo Shik (Jo In Sung), agen veteran yang memiliki kekuatan superhero untuk terbang.",
    poster:
      "https://i.pinimg.com/564x/63/a1/a5/63a1a58f4b0b5dc92cf5d33b21d7ce67.jpg",
    trailer: "https://youtu.be/NbHy4UlQv_s?si=uIH9KpK1WCmXhU3x",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Disney+ Hotstar",
  },
  {
    id: 21,
    title: "Let's Fight Ghost",
    year: 2016,
    genre: ["Action", "Horor", "Misteri", "Comedy"],
    rating: 8.5,
    director: "Yoon Hyun-g",
    actors: ["Kim So-hyun", "Ok Taec-yeon", "Kwon Yul"],
    plot: " Park Bong-pal (Ok Taec-yeon) memiliki kemampuan untuk melihat hantu. Dia menggunakan kekuatannya untuk bekerja sebagai pengusir hantu untuk menghasilkan cukup uang untuk menjalani prosedur yang akan menghilangkan kemampuannya.",
    poster:
      "https://i.pinimg.com/564x/e7/df/13/e7df13e0d0424ff196e635a7771cae34.jpg",
    trailer: "https://youtu.be/YYRMsrBCRYw?si=AK0MHas2kKhd4Tj7",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 22,
    title: "Vagabond",
    year: 2019,
    genre: ["Action", "Romance", "Drama", "Fiksi Criminal"],
    rating: 9.6,
    director: "Shin Sung-rok",
    actors: ["Lee Seung-g", "Bae Suzy", "Moon Jeong-hee"],
    plot: " Sebuah kecelakaan pesawat misterius menewaskan lebih dari 200 warga sipil termasuk keponakan Cha Dal-gun (Lee Seung-gi). Bertekad untuk mencari tahu kebenaran di balik kecelakaan itu, Cha Dal-gun melakukan penyelidikan yang membawanya ke jaringan korupsi yang rumit.",
    poster:
      "https://i.pinimg.com/564x/ba/7e/4b/ba7e4b31b87bf9e7de01589c90bc31ae.jpg",
    trailer: "https://youtu.be/tyhnEHCUtv4?si=jDGDn0co14p3l_3M",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 23,
    title: "He is Psychometric",
    year: 2019,
    genre: ["Action", "Romance", "Drama", "Fiksi"],
    rating: 9.5,
    director: "Kim Byung-soo",
    actors: ["Jinyoung", "Shin Ye-eun", "Go Yoon Jung"],
    plot: "Setelah kehilangan orang tuanya dalam insiden kebakaran apartemen, Lee Ahn (Park Jin-young) mendapatkan kelebihan psikometri, yaitu kemampuan membaca masa lalu orang atau benda melalui kontak fisik, lalu ia menggunakannya untuk menjatuhkan orang-orang jahat di sekitarnya.",
    poster:
      "https://i.pinimg.com/564x/5d/ca/9c/5dca9c156994916d17cbee31fbc16717.jpg",
    trailer: "https://youtu.be/lKW845CdlS8?si=kJ_59qPhnWGW1K9l",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 24,
    title: "Hierarchy",
    year: 2024,
    genre: ["Mistery", "Romance", "Drama"],
    rating: 8.4,
    director: "Bae Hyeon-jin",
    actors: ["Roh Jeong-eui", "Lee Chae-min", "Kim Jae-won"],
    plot: "Hierarchy berkisah tentang kelompok siswa di SMA Jooshin. Ini sekolah swasta bergengsi yang hanya diperuntukkan bagi anak-anak atau siswa dari kelompok 1 persen, orang-orang tajir di Korea. ",
    poster:
      "https://i.pinimg.com/736x/24/a3/70/24a3706ed0ff209932a014406a3277c8.jpg",
    trailer: "https://youtu.be/LQCpNqVa3LU?si=xiGCle7QScIQA2RC",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 25,
    title: "The Golden Spoon",
    year: 2022,
    genre: ["Mistery", "Romance", "Drama", "Fiksi"],
    rating: 8.2,
    director: "Song Hyun-wook",
    actors: ["Yook Sung-jae", "Lee Jong-won,", "Jung Chae-yeon"],
    plot: "The Golden Spoon sendiri merupakan drama fantasi yang menceritakan pertukaran kehidupan seorang siswa miskin bernama Lee Seung Cheon(diperankan oleh Sungjae BTOB) dengan siswa kaya dengan menggunakan sebuah sendok emas.",
    poster:
      "https://i.pinimg.com/564x/e9/62/0e/e9620e04128158ce44fac8f5231ae832.jpg",
    trailer: "https://youtu.be/nilFTYY2cZY?si=sv8dvzjRBtA-Smhr",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Disney+ Hotstar",
  },
  {
    id: 26,
    title: "Hospital Playlist",
    year: 2020,
    genre: ["Hospital", "Romance", "Drama"],
    rating: 9.5,
    director: " Lee Woo Jung",
    actors: ["Jo Jung-suk", "Yoo Yeon-seok", "Jung Kyung-ho"],
    plot: "Tiap hari berjalan luar biasa bagi lima dokter dan para pasien mereka di sebuah rumah sakit, tempat kelahiran, kematian, dan berbagai hal lainnya terjadi.",
    poster:
      "https://i.pinimg.com/564x/c2/6f/56/c26f56c6293e04f80fe184a5cf94e860.jpg",
    trailer: "https://youtu.be/bc8TCfhwAy8?si=iR-m58vNlgqBg4DA",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 27,
    title: "Once Upon a Small Town",
    year: 2022,
    genre: ["Romance", "Drama", "Comedy Romance"],
    rating: 9.7,
    director: "Na Cheol",
    actors: ["Choo Young Woo", "Joy Red Velvet", "Baek Sung-chul"],
    plot: "Melawan keinginannya, seorang dokter hewan dari kota besar pindah ke perdesaan. Di sana, dia bertemu dengan seorang polisi wanita, warga desa yang menyimpan rahasia lama.",
    poster:
      "https://i.pinimg.com/564x/86/eb/5d/86eb5d7c2c1de91fb3761199773204bc.jpg",
    trailer: "https://youtu.be/IQLcz6wLNg0?si=fV7Tl42MpGnFanK4",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 28,
    title: "True Beauty",
    year: 2020,
    genre: ["Romance", "Drama", "Comedy Romance"],
    rating: 9.5,
    director: "Kang Chan-hee",
    actors: ["Moon Ga-young", "Cha Eun-woo", "Hwang In Yeop"],
    plot: "Menceritakan tentang gadis SMA yang diejek karena paras yang jelek, lalu dia belajar merias wajah agar menjadi cantik.",
    poster:
      "https://i.pinimg.com/564x/86/4b/33/864b335a3dfca8ad3107506ecd6ffbd2.jpg",
    trailer: "https://youtu.be/BhP1eYQ5Pxk?si=vZvw0ajVcLzzpUyI",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "TVN",
  },
  {
    id: 29,
    title: "Who are You: School 2015",
    year: 2015,
    genre: ["Romance", "Drama", "Mistery"],
    rating: 9.5,
    director: "Park Doo-shik",
    actors: ["Kim So-hyun", "Nam Joo-hyuk", "Yook Sung-jae"],
    plot: "Kim So Hyun dipercaya membawakan dua karakter sekaligus, yakni gadis kembar Lee Eun Bi dan Go Eun Byul yang merupakan anak kembar identik. Namun keduanya berpisah saat Eun Byul diadopsi. Karena bully di sekolahnya, Lee Eun Bi yang berusaha bunuh diri berhasil diselamatkan oleh Go Eun Byul.",
    poster:
      "https://i.pinimg.com/564x/0a/e9/00/0ae90003ac65229d13898491ae9c5de3.jpg",
    trailer: "https://youtu.be/YoqXPE6qTzo?si=qfYtvEVTT70pInBO",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "KBS",
  },
  {
    id: 30,
    title: "Welcome to Waikiki",
    year: 2018,
    genre: ["Comedy", "Romance", "Drama"],
    rating: 9.6,
    director: "Son Seung-won",
    actors: ["Lee Yi-kyung", "Kim Jung-hyun", "Kim Seon-ho"],
    plot: " Kisah tiga lelaki yang menjalankan usaha penginapan yang gagal bernama Waikiki. Masalah muncul ketika penginapan mereka dikunjungi oleh seorang ibu tunggal dan bayinya.",
    poster:
      "https://i.pinimg.com/564x/d6/76/96/d676967d7f2abfbc499846df661a8aee.jpg",
    trailer: "https://youtu.be/vgQlE_jEvy0?si=Holr2yHSHvt27Ud0",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Iflix",
  },
  {
    id: 31,
    title: "Extraordinary You",
    year: 2019,
    genre: ["Comedy Romance", "Romance", "Drama", "Fantasi"],
    rating: 9.5,
    director: "Kang Full",
    actors: ["Go Yoon Jung", "Lee Jung-ha", "Jo In-sung"],
    plot: "Seri ini bercerita tentang seorang siswi bernama Eun Dan-oh (Kim Hye-yoon) yang bersekolah di sebuah akademi bergengsi. Suatu hari, ia mengetahui bahwa dia dan semua orang di sekolahnya sebenarnya adalah karakter dalam manhwa yang berjudul Secret.",
    poster:
      "https://i.pinimg.com/564x/b3/bb/81/b3bb81cef7df8e792ae41242374a2ec1.jpg",
    trailer: "https://youtu.be/a_1Tf3Rhf6E?si=LJUIzc-Rv11EBPKt",
    runtime: "32 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Kocowa",
  },
  {
    id: 32,
    title: "Strong Girl Bong-soon",
    year: 2017,
    genre: ["Comedy Romance", "Romance", "Drama", "Action"],
    rating: 9.5,
    director: "Kim Won-hae",
    actors: ["Park Bo-young", "Park Hyung-sik", "Ji Soo"],
    plot: "Drama Korea Strong Girl Bong Soon menceritakan tentang kehidupan sehari-hari Do Bong Soon. Terlahir dalam keluarga wanita tangguh, Bong Soon diberkahi dengan sebuah kekuatan super yang luar biasa dan turun-temurun.",
    poster:
      "https://i.pinimg.com/564x/dd/5a/bf/dd5abf64db20a6ecaf4b2274bb7f935f.jpg",
    trailer: "https://youtu.be/ysJzkl-SU1Q?si=AaxfbMF59aIeyxHn",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Iflix",
  },
  {
    id: 33,
    title: "King the Land",
    year: 2023,
    genre: ["Romance", "Drama", "Comedy"],
    rating: 9.4,
    director: "Woo-yeon",
    actors: ["Lee Jun-ho", "Im Yoon-ah"],
    plot: "Di tengah perselisihan sengit soal warisan, seorang ahli waris tampan bertikai dengan karyawannya yang pekerja keras dan terkenal akan senyuman maut—yang membuatnya muak.",
    poster:
      "https://i.pinimg.com/564x/c0/f2/8e/c0f28ef0c47afc069b988a2138e5e8a9.jpg",
    trailer: "https://youtu.be/ny2xZSsLzHA?si=3XPXnVvM2QdkSG_A",
    runtime: "50 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 34,
    title: "Do Do Sol Sol La La Sol",
    year: 2020,
    genre: ["Action", "Romance", "Drama", "Fiksi"],
    rating: 9.5,
    director: "Seo Yi-sook",
    actors: ["Go Ara", "Lee Jae-wook", "Shin Eun-soo"],
    plot: "Drama 'Do Do Sol Sol La La Sol' menceritakan tentang Go Ra Ra (Go Ara) yaitu seorang pianis yang selalu ceria dan riang. Namun pada suatu hari keluarganya bangkrut dan ia frustasi lantaran tidak memiliki uang. Go Ra Ra merasa disinilah titik terendah di hidupnya.",
    poster:
      "https://i.pinimg.com/564x/ca/30/8d/ca308d1732a0fe97eb19e0665286d081.jpg",
    trailer: "https://youtu.be/QJVJsXpdxEQ?si=Xy-OTvbn6ov_vsmj",
    runtime: "40 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 35,
    title: "It's Okay to Not Be Okay",
    year: 2020,
    genre: ["Romance", "Drama", "Fiksi"],
    rating: 8.5,
    director: "Cho Yong",
    actors: ["Kim Soo-hyun", "Seo Yea-ji"],
    plot: "It's Okay to Not Be Okay bercerita tentang dua bersaudara Moon Kang Tae dan Moon Sang Tae. Kang Tae harus menghabiskan sisa hidupnya merawat sang kakak, yakni Sang Tae yang memiliki keterbatasan mental.",
    poster:
      "https://i.pinimg.com/564x/42/49/e9/4249e9740ec9988b1360c5680063a02a.jpg",
    trailer: "https://youtu.be/1H__LNPCc80?si=6cNTHBy7JH4cgENA",
    runtime: "45 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
  {
    id: 36,
    title: "Young Lady and Gentleman",
    year: 2021,
    genre: ["Romance", "Drama"],
    rating: 9.5,
    director: "Cha Hwa-yeon",
    actors: ["Ji Hyun-woo", "Lee Se-hee"],
    plot: "Korean drama bermula dari seorang pria kaya bernama Lee Young Guk yang menjadi single parents setelah sang istri meninggal. Ia memiliki tiga orang anak. Di tengah kesibukannya sebagai pengusaha, Lee Young Guk kemudian mempekerjakan seorang tutor les buat anak-anaknya.",
    poster:
      "https://i.pinimg.com/564x/dd/15/b1/dd15b1d1aa11f9f49fd3ab40cfafc79f.jpg",
    trailer: "https://youtu.be/3vOTb0lnQnU?si=ekHSMd7mLgP8J_i5",
    runtime: "80 minutes per episode",
    country: "South Korea",
    language: "Korean",
    production: "Netflix",
  },
];

const app = express();

app.use(cors());
app.use(express.json());

const router = express.Router();
app.use("/api", router);

router.get("/movie/get-all", (_req, res) => {
  res.json({ message: "Data berhasil didapatkan.", data: movie });
});

app.listen(process.env.API_PORT, () =>
  console.log("Server berhasil dijalankan.")
);
